Repository zstakhiv/App, pull requests merged in 2020-04, with the labels that each got.

#199 Mk master documentation test
  EPlast/EPlast.XUnitTest/DocumentationControllerTests.cs
  EPlast/EPlast/Controllers/AdminController.cs
  EPlast/EPlast/Controllers/DocumentationController.cs
  EPlast/EPlast/EPlast.csproj
  EPlast/EPlast/Notification/NotificationHub.cs
  EPlast/EPlast/Startup.cs
  EPlast/EPlast/Views/Admin/UsersTable.cshtml
  EPlast/EPlast/Views/Documentation/CreateDecesion.cshtml
  EPlast/EPlast/Views/Documentation/ReadDecesion.cshtml
  EPlast/EPlast/wwwroot/uncompiled/sass/documens.scss
  EPlast/EPlast/wwwroot/uncompiled/ts/clubAdmins.js
  EPlast/EPlast/wwwroot/uncompiled/ts/clubAdmins.js.map
  EPlast/EPlast/wwwroot/uncompiled/ts/decesion.js
  EPlast/EPlast/wwwroot/uncompiled/ts/decesion.js.map
  EPlast/EPlast/wwwroot/uncompiled/ts/mainMenu.js
  EPlast/EPlast/wwwroot/uncompiled/ts/mainMenu.js.map
  EPlast/EPlast/wwwroot/uncompiled/ts/mainMenu.ts
Labels: Status: Review Needed

#200 Add test check for actions
  .github/workflows/dotnetcore.yml
Labels: Status: Review Needed

#208 VV Fix main links
  EPlast/EPlast/Views/Shared/_LoginPartial.cshtml
  EPlast/EPlast/wwwroot/uncompiled/ts/mainMenu.js
  EPlast/EPlast/wwwroot/uncompiled/ts/mainMenu.js.map
  EPlast/EPlast/wwwroot/uncompiled/ts/mainMenu.ts
Labels: Configuration, Enhancement

#218 AS-fixed some problems in views
  EPlast/EPlast/Controllers/AccountController.cs
  EPlast/EPlast/Controllers/HomeController.cs
  EPlast/EPlast/Views/Account/ChangePasswordNotAllowed.cshtml
  EPlast/EPlast/Views/Account/Register.cshtml
  EPlast/EPlast/Views/Shared/_LoginPartial.cshtml
Labels: Configuration

#229 AS-Fixed problems with regex
  EPlast/EPlast/ViewModels/Account/ContactsViewModel.cs
  EPlast/EPlast/ViewModels/Account/RegisterViewModel.cs
Labels: Configuration

#237 Test-UserProfile
  EPlast/EPlast.XUnitTest/AccountControllerTests.cs
  EPlast/EPlast/Controllers/AccountController.cs
  EPlast/EPlast/ViewModels/UserViewModel.cs
  EPlast/EPlast/Views/Account/UserProfile.cshtml
Labels: Enhancement

#244 Mk master documentation tests
  EPlast/EPlast.XUnitTest/DocumentationControllerTests.cs
  EPlast/EPlast/Controllers/DocumentationController.cs
Labels: Configuration

#254 AS-add unit tests for user and fix problems with ui
  EPlast/EPlast.XUnitTest/TestsForAccountControllerAndrii.cs
  EPlast/EPlast/Controllers/AccountController.cs
  EPlast/EPlast/ViewModels/Account/ContactsViewModel.cs
  EPlast/EPlast/ViewModels/Account/ForgotPasswordViewModel.cs
  EPlast/EPlast/ViewModels/Account/LoginViewModel.cs
  EPlast/EPlast/ViewModels/Account/RegisterViewModel.cs
  EPlast/EPlast/ViewModels/Account/ResetPasswordViewModel.cs
Labels: Configuration

#272 AS-Responsive UI for user pages and Add unit tests
  EPlast/EPlast.XUnitTest/EPlast.XUnitTest.csproj
  EPlast/EPlast.XUnitTest/TestsForAccountControllerAndrii.cs
  EPlast/EPlast/Controllers/AccountController.cs
  EPlast/EPlast/Views/Account/ResetPassword.cshtml
  EPlast/EPlast/package-lock.json
  EPlast/EPlast/wwwroot/uncompiled/sass/site.scss
Labels: Configuration, Status: Review Needed

#281 VV fix bugs edit page
  .gitignore
  EPlast/EPlast.DataAccess/Entities/Account/User.cs
  EPlast/EPlast/Controllers/AdminController.cs
  EPlast/EPlast/Views/Account/Edit.cshtml
  EPlast/EPlast/Views/Account/UserProfile.cshtml
  EPlast/EPlast/Views/Shared/_Layout.cshtml
  EPlast/EPlast/libman.json
  EPlast/EPlast/package-lock.json
  EPlast/EPlast/package.json
  EPlast/EPlast/wwwroot/uncompiled/sass/editUserPage.scss
  EPlast/EPlast/wwwroot/uncompiled/ts/adminUser.js
  EPlast/EPlast/wwwroot/uncompiled/ts/adminUser.js.map
  EPlast/EPlast/wwwroot/uncompiled/ts/adminUser.ts
Labels: Enhancement

#298 OO Add Test For EventUser Controller
  EPlast/EPlast.XUnitTest/EventUserControllerTests.cs
  EPlast/EPlast/Controllers/EventUserController.cs
  EPlast/EPlast/ViewModels/Events/EventUserViewModel.cs
  EPlast/EPlast/Views/EventUser/EventUser.cshtml
  EPlast/EPlast/Views/EventUser/_EventInfoModals.cshtml
  EPlast/EPlast/Views/Shared/_Layout.cshtml
  EPlast/EPlast/wwwroot/uncompiled/ts/mainMenu.js
  EPlast/EPlast/wwwroot/uncompiled/ts/mainMenu.js.map
  EPlast/EPlast/wwwroot/uncompiled/ts/mainMenu.ts
Labels: Status: Review Needed

#299 DataTable style editing (and decesion fix)
  EPlast/EPlast/Controllers/AccountController.cs
  EPlast/EPlast/Controllers/AdminController.cs
  EPlast/EPlast/Controllers/DocumentationController.cs
  EPlast/EPlast/Views/Admin/UsersTable.cshtml
  EPlast/EPlast/Views/Documentation/ReadDecesion.cshtml
  EPlast/EPlast/Views/Documentation/_CreateDecesion.cshtml
  EPlast/EPlast/wwwroot/uncompiled/sass/DataTable.scss
  EPlast/EPlast/wwwroot/uncompiled/sass/admin_actions.scss
  EPlast/EPlast/wwwroot/uncompiled/sass/documens.scss
  EPlast/EPlast/wwwroot/uncompiled/sass/mainMenu.scss
  EPlast/EPlast/wwwroot/uncompiled/ts/adminUser.js
  EPlast/EPlast/wwwroot/uncompiled/ts/adminUser.js.map
  EPlast/EPlast/wwwroot/uncompiled/ts/adminUser.ts
  EPlast/EPlast/wwwroot/uncompiled/ts/decesion.js
  EPlast/EPlast/wwwroot/uncompiled/ts/decesion.js.map
  EPlast/EPlast/wwwroot/uncompiled/ts/decesion.ts
  EPlast/EPlast/wwwroot/uncompiled/ts/mainMenu.js
  EPlast/EPlast/wwwroot/uncompiled/ts/mainMenu.ts
Labels: Configuration, Enhancement

#301 this is not hot fix for date in decesion
  EPlast/EPlast/Controllers/DocumentationController.cs
  EPlast/EPlast/Startup.cs
  EPlast/EPlast/Wrapper/Services/FileStreamManager.cs
  EPlast/EPlast/wwwroot/uncompiled/ts/decesion.js
  EPlast/EPlast/wwwroot/uncompiled/ts/decesion.js.map
  EPlast/EPlast/wwwroot/uncompiled/ts/decesion.ts
Labels: Type: Maintenances

#303 Mk master decesion edit
  EPlast/EPlast.DataAccess/Repositories/Contracts/IRepositoryWrapper.cs
  EPlast/EPlast/Controllers/DocumentationController.cs
  EPlast/EPlast/Notification/NotificationHub.cs
  EPlast/EPlast/Views/Documentation/ReadDecesion.cshtml
  EPlast/EPlast/Views/Documentation/_EditDecesion.cshtml
  EPlast/EPlast/libman.json
  EPlast/EPlast/wwwroot/uncompiled/ts/decesion.js
  EPlast/EPlast/wwwroot/uncompiled/ts/decesion.js.map
  EPlast/EPlast/wwwroot/uncompiled/ts/decesion.ts
Labels: Configuration, Enhancement

#308 AS-unit tests for account controller and fixed some bugs
  EPlast/EPlast.XUnitTest/AccountControllerTestsIdentity.cs
  EPlast/EPlast.XUnitTest/EPlast.XUnitTest.csproj
  EPlast/EPlast.XUnitTest/TestsForAccountControllerAndrii.cs
  EPlast/EPlast/Controllers/AccountController.cs
  EPlast/EPlast/Views/Account/AcceptingEmailNotAllowed.cshtml
Labels: Configuration, Status: Accepted

#315 Ih city add button
  EPlast/EPlast/Controllers/CItyController.cs
  EPlast/EPlast/Views/City/CityAdmins.cshtml
  EPlast/EPlast/Views/City/CityDocuments.cshtml
  EPlast/EPlast/Views/City/CityFollowers.cshtml
  EPlast/EPlast/Views/City/CityMembers.cshtml
  EPlast/EPlast/Views/City/CityProfile.cshtml
  EPlast/EPlast/Views/City/CityProfile.cshtml.cs
  EPlast/EPlast/Views/City/Create.cshtml
  EPlast/EPlast/Views/City/Create.cshtml.cs
  EPlast/EPlast/Views/City/Details.cshtml
  EPlast/EPlast/Views/City/Edit.cshtml
  EPlast/EPlast/Views/City/Edit.cshtml.cs
  EPlast/EPlast/Views/City/Index.cshtml
  EPlast/EPlast/Views/Home/Index.cshtml
  EPlast/EPlast/Views/Shared/_Layout.cshtml
  EPlast/EPlast/package-lock.json
  EPlast/EPlast/wwwroot/uncompiled/sass/city.scss
  EPlast/EPlast/wwwroot/uncompiled/sass/homePage.scss
Labels: Enhancement, Type: Enhancement

#332 AS-Add responsive UI for account views
  EPlast/EPlast.XUnitTest/AccountControllerTestsIdentity.cs
  EPlast/EPlast/Controllers/AccountController.cs
  EPlast/EPlast/Startup.cs
  EPlast/EPlast/Views/Account/ChangePassword.cshtml
  EPlast/EPlast/Views/Account/ForgotPassword.cshtml
  EPlast/EPlast/Views/Account/Login.cshtml
  EPlast/EPlast/Views/Account/Register.cshtml
  EPlast/EPlast/Views/Account/ResetPassword.cshtml
  EPlast/EPlast/Views/Home/Contacts.cshtml
  EPlast/EPlast/wwwroot/uncompiled/sass/site.scss
Labels: Configuration, Status: Review Needed

#333 Changed time in startup for email token
  EPlast/EPlast/Controllers/AccountController.cs
  EPlast/EPlast/Startup.cs
Labels: Configuration

#339 add create city page
  EPlast/EPlast/Controllers/CItyController.cs
  EPlast/EPlast/Views/City/CityProfile.cshtml.cs
  EPlast/EPlast/Views/City/Create.cshtml
  EPlast/EPlast/Views/City/Create.cshtml.cs
  EPlast/EPlast/wwwroot/images/Cities/333493fe-9c81-489f-bce3-5d1ba35a8c36.jpg
  EPlast/EPlast/wwwroot/images/Cities/4ce571c4-a5ff-43fa-9ae5-a47b476bdc75.jpg
  EPlast/EPlast/wwwroot/images/Club/7f54bc93-4e8b-40d4-9ab5-421f0594b834.png
  EPlast/EPlast/wwwroot/images/defaultForCities.jpg
Labels: Enhancement

#351 AS-Fix Some Bugs
  EPlast/EPlast.XUnitTest/AccountControllerTestsIdentity.cs
  EPlast/EPlast/Views/Account/ChangePassword.cshtml
  EPlast/EPlast/Views/Account/ForgotPassword.cshtml
  EPlast/EPlast/Views/Account/Login.cshtml
  EPlast/EPlast/Views/Account/ResetPassword.cshtml
  EPlast/EPlast/Views/Account/UserProfile.cshtml
  EPlast/EPlast/wwwroot/uncompiled/sass/site.scss
Labels: Configuration

#350 Ih update create page
  EPlast/EPlast.DataAccess/Entities/City.cs
  EPlast/EPlast/Controllers/CItyController.cs
  EPlast/EPlast/Controllers/HomeController.cs
  EPlast/EPlast/Views/Account/AcceptingEmail.cshtml
  EPlast/EPlast/Views/Account/AcceptingEmailNotAllowed.cshtml
  EPlast/EPlast/Views/Account/AccountLocked.cshtml
  EPlast/EPlast/Views/Account/ChangePassword.cshtml
  EPlast/EPlast/Views/City/CityAdmins.cshtml
  EPlast/EPlast/Views/City/CityDocuments.cshtml
  EPlast/EPlast/Views/City/CityFollowers.cshtml
  EPlast/EPlast/Views/City/CityMembers.cshtml
  EPlast/EPlast/Views/City/CityProfile.cshtml
  EPlast/EPlast/Views/City/Create.cshtml
  EPlast/EPlast/Views/City/Details.cshtml
  EPlast/EPlast/Views/City/Edit.cshtml
  EPlast/EPlast/Views/City/Index.cshtml
  EPlast/EPlast/Views/Home/FeedBackSended.cshtml
  EPlast/EPlast/Views/Home/Search.cshtml
  EPlast/EPlast/wwwroot/images/Cities/1cf4ab4f-1dbf-4a4c-a6fc-cb35a207448d.jpg
  EPlast/EPlast/wwwroot/images/Cities/4ce571c4-a5ff-43fa-9ae5-a47b476bdc75.jpg
  EPlast/EPlast/wwwroot/images/Cities/5c13d65c-9258-4019-b0b4-d5626f9199d1.png
  EPlast/EPlast/wwwroot/images/Cities/616fe229-7508-4b58-90c8-039858c7503b.jpg
  EPlast/EPlast/wwwroot/images/Cities/719942ed-dc9c-4e9c-961f-571bbb4cfb35.png
  EPlast/EPlast/wwwroot/images/Cities/add_new_city.png
  EPlast/EPlast/wwwroot/images/chooseImg.png
  EPlast/EPlast/wwwroot/images/defaultForCities.jpg
  EPlast/EPlast/wwwroot/uncompiled/sass/city.scss
  EPlast/EPlast/wwwroot/uncompiled/sass/homePage.scss
Labels: Type: Enhancement

#359 AS-fix bugs
  EPlast/EPlast/Views/Account/ConfirmEmailNotAllowed.cshtml
  EPlast/EPlast/Views/Account/ConfirmedEmail.cshtml
  EPlast/EPlast/Views/Account/ForgotPassword.cshtml
  EPlast/EPlast/Views/Account/ForgotPasswordConfirmation.cshtml
  EPlast/EPlast/Views/Account/Login.cshtml
  EPlast/EPlast/Views/Account/Register.cshtml
  EPlast/EPlast/Views/Account/ResendEmailConfirmation.cshtml
  EPlast/EPlast/Views/Account/ResetPassword.cshtml
  EPlast/EPlast/Views/Account/ResetPasswordConfirmation.cshtml
  EPlast/EPlast/Views/Account/ResetPasswordNotAllowed.cshtml
  EPlast/EPlast/wwwroot/uncompiled/sass/homePage.scss
Labels: Configuration
