Repository zstakhiv/App, pull requests merged in 2020-03, with the labels that each got.

#36 Added Inlcude and Attach for IRepositoryWrapper
  EPlast/EPlast.DataAccess/Repositories/Contracts/IRepositoryBase.cs
  EPlast/EPlast.DataAccess/Repositories/RepositoryBase.cs
Labels: Configuration, Status: Review Needed

#40 Edited Create and Read Raport. back controller with database work too
  EPlast/EPlast/Controllers/ReportController.cs
  EPlast/EPlast/Views/Report/CreateRaport.cshtml
  EPlast/EPlast/Views/Report/ReadRaport.cshtml
  EPlast/EPlast/wwwroot/js/site.js
Labels: Status: Review Needed, enhancement

#43 Deleted AppSettingsJson.cs
  EPlast/EPlast/Models/AppSettingsJson.cs
Labels: Configuration, Status: Completed, Status: Review Needed

#45 Added new EMPTY soltion EPlast.BussinessLayer
  EPlast/EPlast.BussinessLayer/EPlast.BussinessLayer.csproj
  EPlast/EPlast.sln
Labels: Configuration, Status: Review Needed

#61 Added inject to View's and ts function, that auto complete hidden input
  EPlast/EPlast/Controllers/ReportController.cs
  EPlast/EPlast/ViewModels/DecesionViewModel.cs
  EPlast/EPlast/Views/Report/CreateRaport.cshtml
  EPlast/EPlast/Views/Report/ReadRaport.cshtml
  EPlast/EPlast/wwwroot/uncompiled/ts/site.js
  EPlast/EPlast/wwwroot/uncompiled/ts/site.js.map
  EPlast/EPlast/wwwroot/uncompiled/ts/site.ts
Labels: Status: Review Needed, Type: Maintenances

#68 Replace logging to NLog.Web.AspNetCore
  EPlast/EPlast.BussinessLayer/EPlast.BussinessLayer.csproj
  EPlast/EPlast.DataAccess/EPlast.DataAccess.csproj
  EPlast/EPlast/Controllers/AccountController.cs
  EPlast/EPlast/EPlast.csproj
  EPlast/EPlast/Program.cs
  EPlast/EPlast/nlog.config
Labels: Configuration, Enhancement, Status: Review Needed, Type: Enhancement

#71 Edit datepticker for Birthday of User
  EPlast/EPlast.DataAccess/Entities/UserProfile.cs
  EPlast/EPlast/Views/Account/Edit.cshtml
  EPlast/EPlast/wwwroot/uncompiled/ts/site.js
  EPlast/EPlast/wwwroot/uncompiled/ts/site.js.map
  EPlast/EPlast/wwwroot/uncompiled/ts/site.ts
Labels: Enhancement

#72 Move PDF creator logic from Model to BusinessLogic and other fix
  EPlast/EPlast.BussinessLayer/EPlast.BussinessLayer.csproj
  EPlast/EPlast.BussinessLayer/Interfaces/IPDFService.cs
  EPlast/EPlast.BussinessLayer/Services/PDFCreator.cs
  EPlast/EPlast.BussinessLayer/Services/PDFService.cs
  EPlast/EPlast/Controllers/ReportController.cs
  EPlast/EPlast/Models/PDFCreator.cs
  EPlast/EPlast/Views/Report/ReadRaport.cshtml
  EPlast/EPlast/Views/Shared/_Layout.cshtml
  EPlast/EPlast/gulpfile.js
  EPlast/EPlast/package-lock.json
  EPlast/EPlast/package.json
  EPlast/EPlast/wwwroot/images/pdf/Header-Eplast.png
  EPlast/EPlast/wwwroot/uncompiled/ts/mainMenu.js.map
  EPlast/EPlast/wwwroot/uncompiled/ts/mainMenu.ts
  EPlast/EPlast/wwwroot/uncompiled/ts/site.js
  EPlast/EPlast/wwwroot/uncompiled/ts/site.js.map
  EPlast/EPlast/wwwroot/uncompiled/ts/site.ts
Labels: Configuration, Enhancement, Status: Review Needed

#107 Add styles in Confirmed and Accepting pages
  EPlast/EPlast/Views/Account/AcceptingEmail.cshtml
  EPlast/EPlast/Views/Account/ConfirmedEmail.cshtml
Labels: Configuration, Status: Accepted

#110 TypeScriptCompileBlocked true
  EPlast/EPlast/EPlast.csproj
Labels: Configuration

#113 VV fix edit user
  EPlast/EPlast/Controllers/AccountController.cs
Labels: Enhancement

#109 Adding .Net Core Action
  .github/workflows/dotnetcore.yml
Labels: Configuration, Enhancement

#115 Libman fix
  EPlast/EPlast/Views/Report/ReadRaport.cshtml
  EPlast/EPlast/libman.json
Labels: Configuration, Status: Review Needed

#116 MK-master-New-Project
  EPlast/EPlast.XUnitTest/EPlast.XUnitTest.csproj
  EPlast/EPlast.sln
Labels: Configuration, Status: Review Needed

#119 AS add validation and fixing problems
  EPlast/EPlast.DataAccess/Entities/Account/User.cs
  EPlast/EPlast/Controllers/AccountController.cs
  EPlast/EPlast/Startup.cs
  EPlast/EPlast/ViewModels/LoginViewModel.cs
  EPlast/EPlast/ViewModels/RegisterViewModel.cs
  EPlast/EPlast/Views/Account/LoginAndRegister.cshtml
  EPlast/EPlast/Views/Account/UserProfile.cshtml
  EPlast/EPlast/Views/Shared/_LoginPartial.cshtml
  EPlast/EPlast/appsettings.json
  EPlast/EPlast/wwwroot/uncompiled/sass/site.scss
Labels: Configuration, Status: Review Needed

#121 AS-Recovering Password
  EPlast/EPlast.BussinessLayer/Services/EmailConfirmation.cs
  EPlast/EPlast/Controllers/AccountController.cs
  EPlast/EPlast/ViewModels/Account/ForgotPasswordViewModel.cs
  EPlast/EPlast/ViewModels/Account/LoginViewModel.cs
  EPlast/EPlast/ViewModels/Account/RegisterViewModel.cs
  EPlast/EPlast/ViewModels/Account/ResetPasswordViewModel.cs
  EPlast/EPlast/Views/Account/AcceptingEmail.cshtml
  EPlast/EPlast/Views/Account/ConfirmedEmail.cshtml
  EPlast/EPlast/Views/Account/ForgotPassword.cshtml
  EPlast/EPlast/Views/Account/ForgotPasswordConfirmation.cshtml
  EPlast/EPlast/Views/Account/LoginAndRegister.cshtml
  EPlast/EPlast/Views/Account/ResetPassword.cshtml
  EPlast/EPlast/Views/Account/ResetPasswordConfirmation.cshtml
  EPlast/EPlast/wwwroot/uncompiled/sass/site.scss
Labels: Configuration, Status: Review Needed

#129 AS-change login and register page
  EPlast/EPlast/Controllers/AccountController.cs
  EPlast/EPlast/EPlast.csproj
  EPlast/EPlast/ViewModels/Account/LoginViewModel.cs
  EPlast/EPlast/ViewModels/Account/RegisterViewModel.cs
  EPlast/EPlast/Views/Account/ForgotPassword.cshtml
  EPlast/EPlast/Views/Account/Login.cshtml
  EPlast/EPlast/Views/Account/Register.cshtml
  EPlast/EPlast/Views/Account/ResetPassword.cshtml
  EPlast/EPlast/Views/Shared/_Layout.cshtml
  EPlast/EPlast/wwwroot/uncompiled/sass/site.scss
  EPlast/EPlast/wwwroot/uncompiled/ts/mainMenu.js
  EPlast/EPlast/wwwroot/uncompiled/ts/site.js
  EPlast/EPlast/wwwroot/uncompiled/ts/site.js.map
  EPlast/EPlast/wwwroot/uncompiled/ts/site.ts
Labels: Configuration, Status: Review Needed

#143 AS-add Google and Facebook authentication
  EPlast/EPlast/Controllers/AccountController.cs
  EPlast/EPlast/Properties/launchSettings.json
  EPlast/EPlast/Startup.cs
  EPlast/EPlast/ViewModels/Account/ForgotPasswordViewModel.cs
  EPlast/EPlast/ViewModels/Account/LoginViewModel.cs
  EPlast/EPlast/ViewModels/Account/RegisterViewModel.cs
  EPlast/EPlast/ViewModels/Account/ResetPasswordViewModel.cs
  EPlast/EPlast/Views/Account/AcceptingEmail.cshtml
  EPlast/EPlast/Views/Account/AccountLocked.cshtml
  EPlast/EPlast/Views/Account/ConfirmedEmail.cshtml
  EPlast/EPlast/Views/Account/ForgotPassword.cshtml
  EPlast/EPlast/Views/Account/ForgotPasswordConfirmation.cshtml
  EPlast/EPlast/Views/Account/Login.cshtml
  EPlast/EPlast/Views/Account/LoginAndRegister.cshtml
  EPlast/EPlast/Views/Account/ResetPassword.cshtml
  EPlast/EPlast/Views/Account/ResetPasswordConfirmation.cshtml
  EPlast/EPlast/Views/Shared/_LoginPartial.cshtml
  EPlast/EPlast/wwwroot/uncompiled/sass/site.scss
Labels: Configuration, Status: Review Needed

#142 VV-Delete-inject
  EPlast/EPlast/Controllers/AccountController.cs
  EPlast/EPlast/ViewModels/EditUserViewModel.cs
  EPlast/EPlast/Views/Account/Edit.cshtml
Labels: Enhancement

#147 AS-Change Password for user account
  EPlast/EPlast/Controllers/AccountController.cs
  EPlast/EPlast/ViewModels/Account/ChangePasswordViewModel.cs
  EPlast/EPlast/Views/Account/ChangePassword.cshtml
  EPlast/EPlast/Views/Account/ChangePasswordConfirmation.cshtml
  EPlast/EPlast/Views/Shared/_Layout.cshtml
Labels: Configuration, Status: Review Needed

#145 Create Users table for Admin
  EPlast/EPlast.BussinessLayer/Interfaces/IPDFService.cs
  EPlast/EPlast.BussinessLayer/Services/PDFService.cs
  EPlast/EPlast.DataAccess/Entities/Region.cs
  EPlast/EPlast.XUnitTest/EPlast.XUnitTest.csproj
  EPlast/EPlast/Controllers/AccountController.cs
  EPlast/EPlast/Controllers/ActionController.cs
  EPlast/EPlast/Controllers/AdminController.cs
  EPlast/EPlast/Controllers/ClubController.cs
  EPlast/EPlast/Controllers/ErrorController.cs
  EPlast/EPlast/Controllers/EventUserController.cs
  EPlast/EPlast/Controllers/HomeController.cs
  EPlast/EPlast/Controllers/ReportController.cs
  EPlast/EPlast/Startup.cs
  EPlast/EPlast/ViewModels/UserTableViewModel.cs
  EPlast/EPlast/Views/Admin/Index.cshtml
  EPlast/EPlast/Views/Admin/UsersTable.cshtml
  EPlast/EPlast/Views/Report/CreateRaport.cshtml
  EPlast/EPlast/Views/Report/ReadRaport.cshtml
  EPlast/EPlast/wwwroot/uncompiled/sass/raport.scss
Labels: Enhancement, Status: Review Needed

#150 AS-Fix problems in Account Controller
  EPlast/EPlast/Controllers/AccountController.cs
Labels: Configuration

#154 New futures for deploying and style fix
  EPlast/EPlast/.config/dotnet-tools.json
  EPlast/EPlast/EPlast.csproj
  EPlast/EPlast/Views/Error/_ErrorLayout.cshtml
  EPlast/EPlast/Views/Shared/_Layout.cshtml
  EPlast/EPlast/Views/Shared/_LayoutWithoutFooter.cshtml
  EPlast/EPlast/Views/Shared/_ValidationScriptsPartial.cshtml
  EPlast/EPlast/libman.json
Labels: Configuration, Enhancement, Status: Review Needed

#157 Ha club view clickable
  EPlast/EPlast/Controllers/ClubController.cs
  EPlast/EPlast/EPlast.csproj
  EPlast/EPlast/Views/Club/Club.cshtml
  EPlast/EPlast/Views/Club/ClubAdmins.cshtml
  EPlast/EPlast/Views/Club/ClubDescription.cshtml
  EPlast/EPlast/Views/Club/ClubFollowers.cshtml
  EPlast/EPlast/Views/Club/ClubMembers.cshtml
  EPlast/EPlast/wwwroot/uncompiled/sass/allClubs.scss
  EPlast/EPlast/wwwroot/uncompiled/sass/club.scss
  EPlast/EPlast/wwwroot/uncompiled/sass/clubDescription.scss
  EPlast/EPlast/wwwroot/uncompiled/sass/mainMenu.scss
  EPlast/EPlast/wwwroot/uncompiled/ts/clubAdmins.js
  EPlast/EPlast/wwwroot/uncompiled/ts/clubAdmins.js.map
  EPlast/EPlast/wwwroot/uncompiled/ts/clubAdmins.ts
Labels: Status: Review Needed

#168 AS-Add Feedback Logic
  EPlast/EPlast.BussinessLayer/Interfaces/IEmailConfirmation.cs
  EPlast/EPlast.BussinessLayer/Services/EmailConfirmation.cs
  EPlast/EPlast/Controllers/AccountController.cs
  EPlast/EPlast/Controllers/HomeController.cs
  EPlast/EPlast/Startup.cs
  EPlast/EPlast/ViewModels/Account/ChangePasswordViewModel.cs
  EPlast/EPlast/ViewModels/Account/ContactsViewModel.cs
  EPlast/EPlast/Views/Account/ChangePassword.cshtml
  EPlast/EPlast/Views/Account/Edit.cshtml
  EPlast/EPlast/Views/Account/Login.cshtml
  EPlast/EPlast/Views/Account/Register.cshtml
  EPlast/EPlast/Views/Home/Contacts.cshtml
Labels: Configuration, Status: Review Needed

#169 Mk master refactoring
  .gitignore
  EPlast/EPlast.BussinessLayer/PDF/Documents/DecisionDocument.cs
  EPlast/EPlast.DataAccess/Entities/Decesion.cs
  EPlast/EPlast.DataAccess/Entities/DecesionStatus.cs
  EPlast/EPlast.DataAccess/Entities/Organization.cs
  EPlast/EPlast.DataAccess/Migrations/20200324230809_Change-Decesion-table.Designer.cs
  EPlast/EPlast.DataAccess/Migrations/20200324230809_Change-Decesion-table.cs
  EPlast/EPlast.DataAccess/Migrations/20200325140430_Delete-Required-from-Organization.Designer.cs
  EPlast/EPlast.DataAccess/Migrations/20200325140430_Delete-Required-from-Organization.cs
  EPlast/EPlast/Controllers/AdminController.cs
  EPlast/EPlast/Controllers/DocumentationController.cs
  EPlast/EPlast/EPlast.csproj
  EPlast/EPlast/Models/ViewModelInitializations/DecisionVMIitializer.cs
  EPlast/EPlast/Models/ViewModelInitializations/Interfaces/IDecisionVMIitializer.cs
  EPlast/EPlast/Startup.cs
  EPlast/EPlast/ViewModels/DecesionViewModel.cs
  EPlast/EPlast/Views/Documentation/CreateAnnualReport.cshtml
  EPlast/EPlast/Views/Documentation/CreateDecesion.cshtml
  EPlast/EPlast/Views/Documentation/ReadDecesion.cshtml
  EPlast/EPlast/Views/Documentation/ViewAnnualReports.cshtml
  EPlast/EPlast/Views/Documentation/index.cshtml
  EPlast/EPlast/Views/Shared/_Layout.cshtml
  EPlast/EPlast/wwwroot/uncompiled/sass/documens.scss
  EPlast/EPlast/wwwroot/uncompiled/sass/mainMenu.scss
  EPlast/EPlast/wwwroot/uncompiled/ts/decesion.js
  EPlast/EPlast/wwwroot/uncompiled/ts/decesion.js.map
  EPlast/EPlast/wwwroot/uncompiled/ts/decesion.ts
  EPlast/EPlast/wwwroot/uncompiled/ts/mainMenu.js
  EPlast/EPlast/wwwroot/uncompiled/ts/mainMenu.js.map
  EPlast/EPlast/wwwroot/uncompiled/ts/mainMenu.ts
  EPlast/EPlast/wwwroot/uncompiled/ts/raport.js.map
  EPlast/EPlast/wwwroot/uncompiled/ts/site.js.map
Labels: Configuration, Enhancement, Status: Review Needed

#176 VV-Region and administration page
  EPlast/EPlast/Controllers/AccountController.cs
  EPlast/EPlast/Controllers/AdminController.cs
  EPlast/EPlast/ViewModels/RegionsAdminsViewModel.cs
  EPlast/EPlast/Views/Account/UserProfile.cshtml
  EPlast/EPlast/Views/Admin/GetAdmins.cshtml
  EPlast/EPlast/Views/Admin/RegionsAdmins.cshtml
  EPlast/EPlast/wwwroot/uncompiled/sass/admin_actions.scss
  EPlast/EPlast/wwwroot/uncompiled/ts/adminUser.js
  EPlast/EPlast/wwwroot/uncompiled/ts/adminUser.js.map
  EPlast/EPlast/wwwroot/uncompiled/ts/adminUser.ts
  EPlast/EPlast/wwwroot/uncompiled/ts/mainMenu.js
  EPlast/EPlast/wwwroot/uncompiled/ts/mainMenu.ts
Labels: Configuration, Enhancement

#178 AS-add configuration,success feedback view and fixed problems with facebook
  EPlast/EPlast.BussinessLayer/Services/EmailConfirmation.cs
  EPlast/EPlast.BussinessLayer/Settings/EmailServiceSettings.cs
  EPlast/EPlast/Controllers/AccountController.cs
  EPlast/EPlast/Controllers/HomeController.cs
  EPlast/EPlast/Startup.cs
  EPlast/EPlast/Views/Home/Contacts.cshtml
  EPlast/EPlast/Views/Home/FeedBackSended.cshtml
  EPlast/EPlast/Views/Shared/_LoginPartial.cshtml
  EPlast/EPlast/appsettings.json
Labels: Configuration, Status: Review Needed

#179 AS-Fixed problems with Facebook and Changing password
  EPlast/EPlast/Controllers/AccountController.cs
  EPlast/EPlast/Views/Account/ChangePasswordConfirmation.cshtml
  EPlast/EPlast/Views/Account/ForgotPassword.cshtml
  EPlast/EPlast/Views/Account/Login.cshtml
  EPlast/EPlast/Views/Account/Register.cshtml
  EPlast/EPlast/Views/Account/ResetPassword.cshtml
  EPlast/EPlast/Views/Account/UserProfile.cshtml
  EPlast/EPlast/Views/Shared/_Layout.cshtml
Labels: Configuration, Status: Review Needed

#183 VV-Configuration NLog and Add some logs
  EPlast/EPlast/Controllers/AccountController.cs
  EPlast/EPlast/Controllers/AdminController.cs
  EPlast/EPlast/Program.cs
  EPlast/EPlast/Startup.cs
  EPlast/EPlast/nlog.config
Labels: Configuration

#184 VV-Fix bug with registration
  EPlast/EPlast/Controllers/AccountController.cs
Labels: help wanted

#190 MK decision security
  EPlast/EPlast/Controllers/DocumentationController.cs
  EPlast/EPlast/Views/Admin/UsersTable.cshtml
  EPlast/EPlast/Views/Documentation/ReadDecesion.cshtml
  EPlast/EPlast/Views/Shared/_Layout.cshtml
  EPlast/EPlast/wwwroot/uncompiled/sass/documens.scss
Labels: Configuration, Enhancement

#189 Disable-default-asp.net-core-info-logging
  EPlast/EPlast/Program.cs
  EPlast/EPlast/appsettings.json
  EPlast/EPlast/nlog.config
Labels: Configuration
